version: "3.5"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: music
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
